package scheduler;

import java.io.InvalidObjectException;

/**
 * TungHo Lin
 * txl429
 * PA7
 * Class Dependency
 */

public class Dependency {

    private final Assignments child;

    private final Assignments parent;

    private final Relationship relationship;

    public enum Relationship {
        End_Begin, Begin_Begin, Begin_End, End_End;
    }

    public Dependency(Assignments child, Dependency.Relationship relationship, Assignments parent) {
        this.child = child;
        this.relationship = relationship;
        this.parent = parent;
    }

    //autogenerated getter: no testing required
    public Assignments getChild() {
        return child;
    }

    //autogenerated getter: no testing required
    public Assignments getParent() {
        return parent;
    }

    //autogenerated getter: no testing required
    public Relationship getRelationship() {
        return relationship;
    }

    //return true if this and d have the same child and parent Assignments
    public boolean sameChildParent(Dependency d) {
        return this.child.getAssignmentID() == d.child.getAssignmentID() &&
                this.parent.getAssignmentID() == d.parent.getAssignmentID();
    }
}
